### PR TITLE
Fix unnecesary data copy during the curl calls.

### LINKED ISSUE #28423: Indexer connector memory peak during bulk queries
# Description
This issue aims to enhance some memory peaks during the data indexation, basically we are making some copies of long strings during the data processing of the data to be indexed.

# DoD
- [x] Enhance the code to avoid unnecessary data copies.
- [x] Add test to maintain under some limits the memory usage.

### PR DESCRIPTION
**Pull request by Dwordcito**
# Description
This PR aims to remove unnecesary copies during the some methods calls(when we have a data as parameter)

### CODE REVIEW

**Review by pereyra-m — COMMENTED** [review]
Hi @Dwordcito 

I've made a local test and I'm not sure about the result I have.

I've run the `Post100Mbs` test with both the dev branch and `1.0.0`, adding an extra message:

```c++
    std::cout << "RSS usage: " << postPost - prePost << std::endl;
```

These are the results

<details><summary>dev</summary>
<p>

```
root@042fbd6253cf:/workspaces/wazuh-http-request/build/test/component# ./urlrequest_component_test --gtest_filter="*Post100Mbs*"
Note: Google Test filter = *Post100Mbs*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ComponentTestInterface
[ RUN      ] ComponentTestInterface.Post100Mbs
RSS usage: 237320
[       OK ] ComponentTestInterface.Post100Mbs (514 ms)
[----------] 1 test from ComponentTestInterface (514 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (521 ms total)
[  PASSED  ] 1 test.
```

</p>
</details> 

<details><summary>1.0.0</summary>
<p>

```

root@042fbd6253cf:/workspaces/wazuh-http-request/build/test/component# ./urlrequest_component_test --gtest_filter="*Post100Mbs*"
Note: Google Test filter = *Post100Mbs*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ComponentTestInterface
[ RUN      ] ComponentTestInterface.Post100Mbs
RSS usage: 233072
[       OK ] ComponentTestInterface.Post100Mbs (694 ms)
[----------] 1 test from ComponentTestInterface (694 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (700 ms total)
[  PASSED  ] 1 test.
```

</p>
</details> 

This comparison doesn't reflect the improvement in RSS (although it seems faster), what could be the problem?

**Comment by Dwordcito** [comment]
add the log/call(to get the rss) inner the post method in `httpRequest.cpp` because the peak is removed from this section to check the enhancement.

File: include/IURLRequest.hpp
Comment (Damian-Mangold) [inline include/IURLRequest.hpp:1]: Update struct name

https://github.com/wazuh/wazuh-http-request/blob/660021b988c9e57a695a000999377d70306b4230/include/IURLRequest.hpp#L127

File: src/UNIXSocketRequest.cpp [hunk 1]
```diff
@@ -321,15 +384,43 @@ void UNIXSocketRequest::delete_(RequestParameters requestParameters,
...
+                        DeleteRequest::builder(FactoryRequestWrapper<wrapperType>::create(handlerType, shouldRun))};
+                    req.url(arg.url.url(), arg.secureCommunication)
+                        .unixSocketPath(arg.url.unixSocketPath())
+                        .timeout(timeout)
+                        .userAgent(userAgent)
+                        .outputFile(outputFile)
+                        .execute();
+
+                    onSuccess(req.response());
+                }
```
Comment (Damian-Mangold) [inline src/UNIXSocketRequest.cpp]: Is this conditional necessary? Since “data” is not used.

File: test/component/component_test.cpp [hunk 2]
```diff
@@ -433,7 +461,8 @@ TEST_F(ComponentTestInterface, PostHelloWorldFileEmptyURL)
 TEST_F(ComponentTestInterface, PutHelloWorldFile)
```
Comment (Damian-Mangold) [inline test/component/component_test.cpp:484]: How about adding a test to check the behavior when the content of “data” is of type “string”?. I make the comment on this test, but it could be applied to other behavioral checks that currently only check when the type is “json”.

**Review by Damian-Mangold — CHANGES_REQUESTED** [review]
VDP was updated to make use of these changes and no errors were detected in its execution.

```txt
(1/16) ALAS1 Migration: Completed
(2/16) ALAS2 Migration: Completed
(3/16) ALAS2022 Migration: Completed
(4/16) ALAS2023 Migration: Completed
(5/16) AlmaLinux Migration: Completed
(6/16) ArchLinux Migration: Completed
(7/16) NVD Migration: Completed
(8/16) Rocky Migration: Completed
(9/16) Suse Migration: Completed
(10/16) Npm Migration: Completed
(11/16) PyPI Migration: Completed
(12/16) Data Sanitization: Completed
(13/16) Debian Migration: Completed
(14/16) OracleLinux Migration: Completed
(15/16) RedHat Migration: Completed
(16/16) Ubuntu Migration: Completed

(1/1) Content merge: Completed
```

File: test/component/component_test.cpp (hunk 2 above)
Comment (Dwordcito) [reply test/component/component_test.cpp:484]: I will add some basics, I understand that this is pre-existing and we need it quickly in 4.11.1

**Review by Damian-Mangold — APPROVED** [review]
LGTM !

```txt
2025-03-07 09:55:36,215:INFO:root:     Stage 'Content migration (1/3) and sanitization': finished processes 0/9
2025-03-07 09:55:36,216:INFO:root:      (1/9) ALAS1 Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (2/9) ALAS2 Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (3/9) ALAS2022 Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (4/9) ALAS2023 Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (5/9) AlmaLinux Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (6/9) ArchLinux Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (7/9) Npm Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (8/9) PyPI Migration: Running
2025-03-07 09:55:36,216:INFO:root:      (9/9) Data Sanitization: Running
2025-03-07 09:56:08,249:INFO:root:     Stage 'Content migration (1/3) and sanitization': finished processes 9/9
2025-03-07 09:56:08,249:INFO:root:      (1/9) ALAS1 Migration: Completed
2025-03-07 09:56:08,249:INFO:root:      (2/9) ALAS2 Migration: Completed
2025-03-07 09:56:08,249:INFO:root:      (3/9) ALAS2022 Migration: Completed
2025-03-07 09:56:08,249:INFO:root:      (4/9) ALAS2023 Migration: Completed
2025-03-07 09:56:08,249:INFO:root:      (5/9) AlmaLinux Migration: Completed
2025-03-07 09:56:08,249:INFO:root:      (6/9) ArchLinux Migration: Completed
2025-03-07 09:56:08,249:INFO:root:      (7/9) Npm Migration: Completed
2025-03-07 09:56:08,250:INFO:root:      (8/9) PyPI Migration: Completed
2025-03-07 09:56:08,250:INFO:root:      (9/9) Data Sanitization: Completed
2025-03-07 09:56:08,250:INFO:root:   Stage 'Content migration (1/3) and sanitization' finished. Processes completed successfully.
2025-03-07 09:56:08,250:INFO:root:   Starting stage 'Content merge'
2025-03-07 09:56:08,250:INFO:root:     Starting process 'Content merge'
2025-03-07 09:56:08,250:INFO:root:     Waiting for all processes to finish...
2025-03-07 09:56:08,250:INFO:root:     Stage 'Content merge': finished processes 0/1
2025-03-07 09:56:08,250:INFO:root:      (1/1) Content merge: Running
2025-03-07 09:56:31,272:INFO:root:     Stage 'Content merge': finished processes 1/1
2025-03-07 09:56:31,272:INFO:root:      (1/1) Content merge: Completed
2025-03-07 09:56:31,272:INFO:root:   Stage 'Content merge' finished. Processes completed successfully.
2025-03-07 09:56:31,272:INFO:root: Full Pipeline finished.

```

**Review by GabrielEValenzuela — APPROVED** [review]
LGTM
